name: Crypto Analytics V3.0 - Hybrid Schedule

on:
  schedule:
    # Every hour at 0 and 5, then at 15, 30, 45 minutes
    - cron: '0,5,15,30,45 * * * *'
  workflow_dispatch:

jobs:
  crypto-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create cache directories
      run: |
        mkdir -p cache
        mkdir -p logs

    - name: Run Scheduled Crypto Analytics
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        HIGH_RISK_CHAT_ID:     ${{ secrets.HIGH_RISK_CHAT_ID }}
        TELEGRAM_CHAT_ID:      ${{ secrets.TELEGRAM_CHAT_ID }}
        BINGX_API_KEY:         ${{ secrets.BINGX_API_KEY }}
        BINGX_SECRET_KEY:      ${{ secrets.BINGX_SECRET_KEY }}
        COINGECKO_API_KEY:     ${{ secrets.COINGECKO_API_KEY }}
        GITHUB_ACTIONS_MODE:   "true"
      run: |
        echo "🚀 Starting Crypto Analytics V3.0 - Hybrid Schedule"
        python main_scheduled.py

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: crypto-analytics-logs
        path: logs/
        retention-days: 7

    - name: Display recent logs
      if: always()
      run: |
        echo "📈 Execution complete at $(date)"
        if [ -f "logs/github_actions.log" ]; then
          tail -n 10 logs/github_actions.log
        fi
